const customBlocks = [
    {
    "func_name": "SetDestination",
    "desc": "목적지를 설정하는 함수\r\ndestination: 설정하려는 목적지\r\ndelay: 함수 실행 완료 후 딜레이 시간",
    "args1_name": "destination",
    "args1_type": "str",
    "args1_value": "",
    "args2_name": "delay",
    "args2_type": "int",
    "args2_value": "0",
    "args3_name": null,
    "args3_type": null,
    "args3_value": null,
    "args4_name": null,
    "args4_type": null,
    "args4_value": null,
    "args5_name": null,
    "args5_type": null,
    "args5_value": null
    },
    {
    "func_name": "GotoScreen",
    "desc": "화면 이동 함수\r\nscreenName: 이동하려는 화면\r\ndelay: 함수 실행 완료 후 딜레이 시간",
    "args1_name": "screenName",
    "args1_type": "str",
    "args1_value": "",
    "args2_name": "delay",
    "args2_type": "int",
    "args2_value": "0",
    "args3_name": null,
    "args3_type": null,
    "args3_value": null,
    "args4_name": null,
    "args4_type": null,
    "args4_value": null,
    "args5_name": null,
    "args5_type": null,
    "args5_value": null
    }
]