// ChildFrm.h : interface of the CChildFrame class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#pragma once

class CChildFrame : public CMDIChildWnd, CXTPCommandBarsFrameHook
{
	DECLARE_DYNCREATE(CChildFrame)

	// Construction
public:
	CChildFrame();

	// Overrides
public:
	virtual ~CChildFrame();

	virtual BOOL OnCreateClient(LPCREATESTRUCT lpcs, CCreateContext* pContext);
	void OnUpdateMDIChildrenTheme();
	virtual BOOL PreCreateWindow(CREATESTRUCT& cs);

	// Implementation
protected:
	DECLARE_MESSAGE_MAP()

};
