// ChildFrm.cpp : implementation of the CChildFrame class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#include "stdafx.h"

#include "XTPApplication1.h"
#include "XTPApplication1View.h"

#include "ChildFrm.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

IMPLEMENT_DYNCREATE(CChildFrame, CMDIChildWnd)

BEGIN_MESSAGE_MAP(CChildFrame, CMDIChildWnd)
END_MESSAGE_MAP()

CChildFrame::CChildFrame()
{
	// TODO: add member initialization code here
}

CChildFrame::~CChildFrame()
{
	// TODO: add cleanup code here
}

BOOL CChildFrame::OnCreateClient(LPCREATESTRUCT lpcs, CCreateContext* pContext)
{
	if (!CMDIChildWnd::OnCreateClient(lpcs, pContext))
		return FALSE;

	OnUpdateMDIChildrenTheme();

	return TRUE;
}

void CChildFrame::OnUpdateMDIChildrenTheme()
{
	CXTPMDIFrameWnd* pParentFrame = DYNAMIC_DOWNCAST(CXTPMDIFrameWnd, GetParentFrame());
	ASSERT_VALID(pParentFrame);

	CXTPCommandBars* pParentCommandBars = pParentFrame->GetCommandBars();
	ASSERT_VALID(pParentCommandBars);
	EnableFrameTheme(this, pParentCommandBars->GetPaintManager());

	// Send theme update notification to a view
	CXTPApplication1View* pView = DYNAMIC_DOWNCAST(CXTPApplication1View, GetActiveView());
	if (NULL != pView)
	{
		pView->OnThemeChanged();
	}

}

BOOL CChildFrame::PreCreateWindow(CREATESTRUCT& cs)
{
	if (!CMDIChildWnd::PreCreateWindow(cs))
		return FALSE;

	// TODO: Modify the Window class or styles here by modifying the CREATESTRUCT cs

	return TRUE;
}
