// CustomizePageGeneral.cpp : implementation of the CCustomizePageGeneral class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#include "stdafx.h"

#include "XTPApplication1.h"
#include "CustomizePageGeneral.h"
#include "MainFrm.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

IMPLEMENT_DYNCREATE(CCustomizePageGeneral, CXTPPropertyPage)

BEGIN_MESSAGE_MAP(CCustomizePageGeneral, CXTPPropertyPage)
END_MESSAGE_MAP()

CCustomizePageGeneral::CCustomizePageGeneral() 
	: CXTPPropertyPage(CCustomizePageGeneral::IDD)
	, m_bShowKeyboardTips(FALSE)
{
	// TODO: add member initialization code here
}

CCustomizePageGeneral::~CCustomizePageGeneral()
{
	// TODO: add cleanup code here
}

CXTPCommandBars* CCustomizePageGeneral::GetCommandBars() const
{
	CMainFrame* pMainFrame = DYNAMIC_DOWNCAST(CMainFrame, AfxGetMainWnd());
	ASSERT_VALID(pMainFrame);
	return pMainFrame->GetCommandBars();
}

void CCustomizePageGeneral::DoDataExchange(CDataExchange* pDX)
{
	CXTPPropertyPage::DoDataExchange(pDX);
	DDX_Check(pDX, IDC_CUSTOMIZEPAGE_GENERAL_SHOWEYBOARDTIPS, m_bShowKeyboardTips);
	DDX_Control(pDX, IDC_CUSTOMIZEPAGE_GENERAL_CAPTION, m_wndCaption);
	DDX_Control(pDX, IDC_CUSTOMIZEPAGE_GENERAL_TITLE, m_wndTitle);
}

BOOL CCustomizePageGeneral::OnInitDialog()
{
	CXTPPropertyPage::OnInitDialog();

	ModifyStyle(0, WS_CLIPCHILDREN | WS_VSCROLL);
	
	SetResize(IDC_CUSTOMIZEPAGE_GENERAL_CAPTION, XTP_ANCHOR_TOPLEFT, XTP_ANCHOR_TOPRIGHT);

	m_wndTitle.SetMarkupTextEx(_T("<StackPanel Orientation='Horizontal'><Image Source='res://IDB_OPTIONSICON_GENERAL'/>")
		_T("<TextBlock Padding='3, 0, 0, 0' FontSize='13' VerticalAlignment='Center'>%s</TextBlock></StackPanel>"));

	m_wndCaption.SetMarkupTextEx(_T("<Grid Background='#f0f2f5'>")
		_T("<TextBlock Padding='5, 0, 0, 0' FontWeight='Bold' Foreground='#3b3b3b' VerticalAlignment='Center'>%s</TextBlock>")
		_T("<Border Height='1' Background='#e2e4e7' VerticalAlignment='Bottom'/></Grid>"));

	m_bShowKeyboardTips = GetCommandBars()->GetCommandBarsOptions()->bShowKeyboardTips;

	UpdateData(FALSE);
	
	return TRUE;  // return TRUE unless you set the focus to a control
	// EXCEPTION: OCX Property Pages should return FALSE
}

void CCustomizePageGeneral::OnOK() 
{
	UpdateData();

	GetCommandBars()->GetCommandBarsOptions()->bShowKeyboardTips = m_bShowKeyboardTips;

	CXTPPropertyPage::OnOK();
}
