// CustomizePageGeneral.h : interface of the CCustomizePageGeneral class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#pragma once

class CCustomizePageGeneral : public CXTPPropertyPage
{
	DECLARE_DYNCREATE(CCustomizePageGeneral)

// Construction
public:
	CCustomizePageGeneral();

// Overrides
public:
	virtual ~CCustomizePageGeneral();

protected:
	virtual void OnOK();
	virtual void DoDataExchange(CDataExchange* pDX);
	virtual BOOL OnInitDialog();

// Implementation
protected:
	DECLARE_MESSAGE_MAP()

	CXTPCommandBars* GetCommandBars() const;

// Attributes
private:
	enum { IDD = IDD_CUSTOMIZEPAGE_GENERAL };
	BOOL m_bShowKeyboardTips;
	CXTPMarkupStatic m_wndCaption;
	CXTPMarkupStatic m_wndTitle;
};
