// MainFrm.h : interface of the CMainFrame class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#pragma once

#include "Resource.h"

class CXTPApplication1View;

class CMainFrame : public CXTPMDIFrameWnd, CXTPCommandBarsFrameHook
{
	typedef CXTPMDIFrameWnd BaseFrame;

	DECLARE_DYNCREATE(CMainFrame);

// Construction
public:
	CMainFrame();

// Operations
public:
	void EnableTheme(XTPPaintTheme nTheme, LPCTSTR lpzThemeSettings, BOOL bEnable = TRUE);
	void UpdateTheme();

// Overrides
public:
	virtual ~CMainFrame();

	virtual BOOL PreCreateWindow(CREATESTRUCT& cs);

// Implementation
private:
	BOOL CreateRibbonBar();
	void CreateBackstage();
	void DestroyBackstage();
	BOOL CreateTabClient();
	BOOL CreateStatusBar();
	void InitTooltips();
	void SetTooltipStyle(XTPToolTipStyle nStyle);
	void SetFrameIcon(CSize szIcon);
	void UpdateChildrenTheme();
	void DisableStyle();
	void EnableNoStyle(BOOL bEnable = TRUE);
	void EnableStyleOffice2007(BOOL bEnable = TRUE);
	void EnableStyleOffice2010(BOOL bEnable = TRUE);
	void EnableStyleOffice2013(BOOL bEnable = TRUE);
	void EnableStyleOffice2016(BOOL bEnable = TRUE);
	void EnableStyleVisualStudio2015(BOOL bEnable = TRUE);
	void EnableStyleWindows7(BOOL bEnable = TRUE);

	enum OptionsPage {
		xtpOptionsPageGeneral,
		xtpOptionsPageRibbon,
		xtpOptionsPageQAT
	};
	void ShowOptionsDialog(OptionsPage nSelectedPage = xtpOptionsPageGeneral);
	//void LoadDefaultIcons();
	//void Load2013Icons();

protected:
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
	afx_msg void OnDestroy();
	afx_msg void OnSettingChange(UINT uFlags, LPCTSTR lpszSection);
	afx_msg void OnUpdateEnableMDIWindows(CCmdUI* pCmdUI);
	afx_msg void OnWindowArrange();
	afx_msg void OnWindowCascade();
	afx_msg void OnWindowTileHorz();
	afx_msg void OnWindowTileVert();
	afx_msg void OnCustomize();
	afx_msg void OnCustomizeQuickAccess();
	afx_msg void OnOptionsStyle(UINT nStyle);
	afx_msg void OnUpdateOptionsStyle(CCmdUI* pCmdUI);
	DECLARE_MESSAGE_MAP()

// Attributes
protected:
	BOOL m_bThemeApplied;
	XTPPaintTheme m_nAppliedTheme;
	CString m_strAppliedThemeSettings;
	CXTPStatusBar m_wndStatusBar;
	CXTPRibbonBar* m_pRibbonBar;
	CXTPCommandBar* m_pDefaultSystemButtonCommandBar;
	CXTPRibbonBackstageView* m_pBackstageView;
	CXTPRibbonBackstagePageRecent m_wndBackstagePageRecent;
	CXTPTabClientWnd m_wndTabClient;
};
