// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently,
// but are changed infrequently
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#pragma once

#ifndef VC_EXTRALEAN
#define VC_EXTRALEAN            // Exclude rarely-used stuff from Windows headers
#endif

#include "targetver.h"

#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS      // some CString constructors will be explicit

// turns off MFC's hiding of some common and often safely ignored warning messages
#define _AFX_ALL_WARNINGS

#include <afxwin.h>             // MFC core and standard components
#include <afxwinappex.h>
#include <afxext.h>             // MFC extensions
#include <afxdisp.h>            // MFC Automation classes
#include <afxcontrolbars.h>     // MFC support for ribbons and control bars
#ifndef _AFX_NO_OLE_SUPPORT
#include <afxdtctl.h>           // MFC support for Internet Explorer 4 Common Controls
#endif
#ifndef _AFX_NO_AFXCMN_SUPPORT
#include <afxcmn.h>             // MFC support for Windows Common Controls
#endif
#include <afxdhtml.h>           // MFC HTML Dialogs

// Codejock Software Components
#define _XTP_EXCLUDE_CALENDAR           // Toolkit Pro Calendar is not used in the selected configuration
#define _XTP_EXCLUDE_CHART              // Toolkit Pro Chart is not used in the selected configuration
#define _XTP_EXCLUDE_DOCKINGPANE        // Toolkit Pro DockingPane is not used in the selected configuration
#define _XTP_EXCLUDE_FLOWGRAPH          // Toolkit Pro FlowGraph is not used in the selected configuration
#define _XTP_EXCLUDE_PROPERTYGRID       // Toolkit Pro PropertyGrid is not used in the selected configuration
#define _XTP_EXCLUDE_REPORTCONTROL      // Toolkit Pro Report is not used in the selected configuration
#define _XTP_EXCLUDE_SHORTCUTBAR        // Toolkit Pro ShortcutBar is not used in the selected configuration
#define _XTP_EXCLUDE_SKINFRAMEWORK      // Toolkit Pro SkinFramework is not used in the selected configuration
#define _XTP_EXCLUDE_SYNTAXEDIT         // Toolkit Pro SyntaxEdit is not used in the selected configuration
#define _XTP_EXCLUDE_TASKPANEL          // Toolkit Pro TaskPanel is not used in the selected configuration

#include <XTToolkitPro.h>               // The only needed Toolkit Pro inclusion

#ifdef _UNICODE
#if defined _M_IX86
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='x86' publicKeyToken='6595b64144ccf1df' language='*'\"")
#elif defined _M_X64
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='amd64' publicKeyToken='6595b64144ccf1df' language='*'\"")
#else
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
#endif
#endif

