// XTPApplication1Doc.cpp : implementation of the CXTPApplication1Doc class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#include "stdafx.h"

#include "XTPApplication1.h"
#include "XTPApplication1Doc.h"

#include <propkey.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

IMPLEMENT_DYNCREATE(CXTPApplication1Doc, CDocument)

BEGIN_MESSAGE_MAP(CXTPApplication1Doc, CDocument)
END_MESSAGE_MAP()

CXTPApplication1Doc::CXTPApplication1Doc()
{
	// TODO: add member initialization code here
}

CXTPApplication1Doc::~CXTPApplication1Doc()
{
	// TODO: add cleanup code here
}

BOOL CXTPApplication1Doc::OnNewDocument()
{
	if (!CDocument::OnNewDocument())
		return FALSE;

	// TODO: add reinitialization code here
	// (SDI documents will reuse this document)

	return TRUE;
}

void CXTPApplication1Doc::Serialize(CArchive& ar)
{
	if (ar.IsStoring())
	{
		// TODO: add storing code here
	}
	else
	{
		// TODO: add loading code here
	}

	__super::Serialize(ar);
}

