// XTPApplication1.h : main header file for the XTPApplication1 application
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//
#pragma once

#ifndef __AFXWIN_H__
	#error "include 'stdafx.h' before including this file for PCH"
#endif

#include "resource.h"


// CXTPApplication1App:
// See XTPApplication1.cpp for the implementation of this class
//

class CXTPApplication1App : public CXTPWinApp
{
	DECLARE_DYNAMIC(CXTPApplication1App);

public:
	CXTPApplication1App();

// Overrides
public:
	virtual ~CXTPApplication1App();

	virtual BOOL InitInstance();
	virtual int ExitInstance();

public:
	XTPPaintTheme GetAppTheme(XTPPaintTheme nDefaultTheme = xtpThemeNone) const;
	CString GetAppThemeSettings(LPCTSTR lpDefaultSettings = NULL);
	void SetAppTheme(XTPPaintTheme nTheme, LPCTSTR lpThemeSettings = NULL, BOOL bUpdateResources = TRUE);

private:
	void InitVisualStyles();

	static BOOL GetStylesPath(CString& strPath, LPCTSTR lpFileName = NULL);

protected:
	afx_msg void OnAppAbout();
	DECLARE_MESSAGE_MAP()
};

extern CXTPApplication1App theApp;


// CAboutDlg dialog used for App About

class CAboutDlg : public CDialogEx
{
	DECLARE_DYNAMIC(CAboutDlg);

// Construction
public:
	CAboutDlg();

// Dialog Data
public:
	enum { IDD = IDD_ABOUTBOX };

// Overrides
public:
	virtual ~CAboutDlg();

protected:
	virtual void DoDataExchange(CDataExchange* pDX);

// Implementation
protected:
	DECLARE_MESSAGE_MAP()
};
