// XTPApplication1View.h : interface of the CXTPApplication1View class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#pragma once


class CXTPApplication1Doc;
class CMainFrame;

class CXTPApplication1View : public CView
{
	typedef CView ParentView;

	DECLARE_DYNCREATE(CXTPApplication1View);

// Construction
protected:
	CXTPApplication1View();

// Operations
public:
	CXTPApplication1Doc* GetDocument() const;
	CMainFrame* GetMainFrame() const;

// Overrides
public:
	virtual ~CXTPApplication1View();

	virtual BOOL PreCreateWindow(CREATESTRUCT& cs);
	virtual void OnDraw(CDC* pDC);

// Implementation
public:
	void OnThemeChanged();

protected:
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
	afx_msg void OnEmptyCommand();
	afx_msg void OnUpdateEmptyCommand(CCmdUI* pCmdUI);
	DECLARE_MESSAGE_MAP()

// Attributes
private:
};

#ifndef _DEBUG  // debug version in XTPApplication1View.cpp
AFX_INLINE CXTPApplication1Doc* CXTPApplication1View::GetDocument() const
{
	return reinterpret_cast<CXTPApplication1Doc*>(m_pDocument);
}

#endif
