// XTPApplication1Doc.h : interface of the CXTPApplication1Doc class
//
// Generated by Codejock Toolkit Pro Application Wizard.
// Contact information:
//     support@codejock.com
//     http://www.codejock.com
//

#pragma once

class CXTPApplication1Doc : public CDocument
{
	DECLARE_DYNCREATE(CXTPApplication1Doc)

// Construction
protected:
	CXTPApplication1Doc();

// Overrides
public:
	virtual ~CXTPApplication1Doc();

	virtual BOOL OnNewDocument();
	virtual void Serialize(CArchive& ar);

// Implementation
protected:
	DECLARE_MESSAGE_MAP()
};
